const header = document.getElementById("header");
header.style.backgroundColor='green';
header.style.borderBottom = "3px solid orange"
const mainheading = document.getElementById("main-heading");
mainheading.style.color = "orange";
mainheading.textContent = "Fruit World";
const basketheading= document.getElementById("basket-heading");
basketheading.style.color = "green";
const thanks = document.getElementById("thanks");
thanks.innerHTML = "<p>Please visit us again</p>"